name: Deploy Pipeline
on:
  push:
    branches: [ main ]
jobs:
  run: 
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy SageMaker Endpoint 
      id: sm_deploy
      env:
        IAM_ROLE_NAME: ${{ secrets.IAM_ROLE_NAME }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        PREFIX: ${{ secrets.PREFIX }}


      run: |
        pip install --no-cache-dir --upgrade awscli pandas boto3 sagemaker requests
        python deploy.py
